"""añade historia a circuitos

Revision ID: 372edd360431
Revises: a260a8958135
Create Date: 2026-08-13 08:20:05.966076

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '372edd360431'
down_revision: Union[str, Sequence[str], None] = 'a260a8958135'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('circuitos', sa.Column('historia', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('circuitos', 'historia')
    # ### end Alembic commands ###
