"""añade fabricantes, equipos reales, quita columnas rotas de equipo_nombre/constructor_nombre

Revision ID: 427606013f48
Revises: 6ea3e7cbcb90
Create Date: 2026-08-13 11:06:50.600675

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '427606013f48'
down_revision: Union[str, Sequence[str], None] = '6ea3e7cbcb90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('equipos_reales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('precio', sa.Numeric(precision=4, scale=1), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_index(op.f('ix_equipos_reales_id'), 'equipos_reales', ['id'], unique=False)
    op.create_table('fabricantes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('precio', sa.Numeric(precision=4, scale=1), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_index(op.f('ix_fabricantes_id'), 'fabricantes', ['id'], unique=False)
    op.add_column('equipos', sa.Column('fabricante_id', sa.Integer(), nullable=True))
    op.add_column('equipos', sa.Column('equipo_real_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'equipos', 'fabricantes', ['fabricante_id'], ['id'])
    op.create_foreign_key(None, 'equipos', 'equipos_reales', ['equipo_real_id'], ['id'])
    op.drop_column('equipos', 'constructor_nombre')
    op.drop_column('equipos', 'equipo_nombre')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('equipos', sa.Column('equipo_nombre', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('equipos', sa.Column('constructor_nombre', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'equipos', type_='foreignkey')
    op.drop_constraint(None, 'equipos', type_='foreignkey')
    op.drop_column('equipos', 'equipo_real_id')
    op.drop_column('equipos', 'fabricante_id')
    op.drop_index(op.f('ix_fabricantes_id'), table_name='fabricantes')
    op.drop_table('fabricantes')
    op.drop_index(op.f('ix_equipos_reales_id'), table_name='equipos_reales')
    op.drop_table('equipos_reales')
    # ### end Alembic commands ###
