"""elimina campo de más caídas de pronósticos

Revision ID: 6ea3e7cbcb90
Revises: 372edd360431
Create Date: 2026-08-13 09:04:23.831318

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ea3e7cbcb90'
down_revision: Union[str, Sequence[str], None] = '372edd360431'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('pronosticos_caidas_motogp_id_fkey'), 'pronosticos', type_='foreignkey')
    op.drop_constraint(op.f('pronosticos_caidas_moto3_id_fkey'), 'pronosticos', type_='foreignkey')
    op.drop_constraint(op.f('pronosticos_caidas_moto2_id_fkey'), 'pronosticos', type_='foreignkey')
    op.drop_column('pronosticos', 'caidas_moto3_id')
    op.drop_column('pronosticos', 'caidas_moto2_id')
    op.drop_column('pronosticos', 'caidas_motogp_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pronosticos', sa.Column('caidas_motogp_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('pronosticos', sa.Column('caidas_moto2_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('pronosticos', sa.Column('caidas_moto3_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('pronosticos_caidas_moto2_id_fkey'), 'pronosticos', 'pilotos', ['caidas_moto2_id'], ['id'])
    op.create_foreign_key(op.f('pronosticos_caidas_moto3_id_fkey'), 'pronosticos', 'pilotos', ['caidas_moto3_id'], ['id'])
    op.create_foreign_key(op.f('pronosticos_caidas_motogp_id_fkey'), 'pronosticos', 'pilotos', ['caidas_motogp_id'], ['id'])
    # ### end Alembic commands ###
