"""baseline: esquema correcto con unique constraints

Revision ID: 8f38f93de710
Revises: 
Create Date: 2026-07-28 13:50:40.517115

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f38f93de710'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pronosticos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('temporada', sa.Integer(), nullable=False),
    sa.Column('campeon_motogp_id', sa.Integer(), nullable=True),
    sa.Column('segundo_motogp_id', sa.Integer(), nullable=True),
    sa.Column('tercero_motogp_id', sa.Integer(), nullable=True),
    sa.Column('campeon_moto2_id', sa.Integer(), nullable=True),
    sa.Column('segundo_moto2_id', sa.Integer(), nullable=True),
    sa.Column('tercero_moto2_id', sa.Integer(), nullable=True),
    sa.Column('campeon_moto3_id', sa.Integer(), nullable=True),
    sa.Column('segundo_moto3_id', sa.Integer(), nullable=True),
    sa.Column('tercero_moto3_id', sa.Integer(), nullable=True),
    sa.Column('poleman_motogp_id', sa.Integer(), nullable=True),
    sa.Column('poleman_moto2_id', sa.Integer(), nullable=True),
    sa.Column('poleman_moto3_id', sa.Integer(), nullable=True),
    sa.Column('victorias_motogp_id', sa.Integer(), nullable=True),
    sa.Column('victorias_moto2_id', sa.Integer(), nullable=True),
    sa.Column('victorias_moto3_id', sa.Integer(), nullable=True),
    sa.Column('rookie_motogp_id', sa.Integer(), nullable=True),
    sa.Column('rookie_moto2_id', sa.Integer(), nullable=True),
    sa.Column('rookie_moto3_id', sa.Integer(), nullable=True),
    sa.Column('caidas_motogp_id', sa.Integer(), nullable=True),
    sa.Column('caidas_moto2_id', sa.Integer(), nullable=True),
    sa.Column('caidas_moto3_id', sa.Integer(), nullable=True),
    sa.Column('puntos_pronosticos', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['caidas_moto2_id'], ['pilotos.id'], ),
    sa.ForeignKeyConstraint(['caidas_moto3_id'], ['pilotos.id'], ),
    sa.ForeignKeyConstraint(['caidas_motogp_id'], ['pilotos.id'], ),
    sa.ForeignKeyConstraint(['campeon_moto2_id'], ['pilotos.id'], ),
    sa.ForeignKeyConstraint(['campeon_moto3_id'], ['pilotos.id'], ),
    sa.ForeignKeyConstraint(['campeon_motogp_id'], ['pilotos.id'], ),
    sa.ForeignKeyConstraint(['poleman_moto2_id'], ['pilotos.id'], ),
    sa.ForeignKeyConstraint(['poleman_moto3_id'], ['pilotos.id'], ),
    sa.ForeignKeyConstraint(['poleman_motogp_id'], ['pilotos.id'], ),
    sa.ForeignKeyConstraint(['rookie_moto2_id'], ['pilotos.id'], ),
    sa.ForeignKeyConstraint(['rookie_moto3_id'], ['pilotos.id'], ),
    sa.ForeignKeyConstraint(['rookie_motogp_id'], ['pilotos.id'], ),
    sa.ForeignKeyConstraint(['segundo_moto2_id'], ['pilotos.id'], ),
    sa.ForeignKeyConstraint(['segundo_moto3_id'], ['pilotos.id'], ),
    sa.ForeignKeyConstraint(['segundo_motogp_id'], ['pilotos.id'], ),
    sa.ForeignKeyConstraint(['tercero_moto2_id'], ['pilotos.id'], ),
    sa.ForeignKeyConstraint(['tercero_moto3_id'], ['pilotos.id'], ),
    sa.ForeignKeyConstraint(['tercero_motogp_id'], ['pilotos.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['victorias_moto2_id'], ['pilotos.id'], ),
    sa.ForeignKeyConstraint(['victorias_moto3_id'], ['pilotos.id'], ),
    sa.ForeignKeyConstraint(['victorias_motogp_id'], ['pilotos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pronosticos_id'), 'pronosticos', ['id'], unique=False)
    op.create_index(op.f('ix_carreras_id'), 'carreras', ['id'], unique=False)
    op.alter_column('equipos', 'usuario_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('equipos', 'carrera_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('equipos', 'temporada',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('equipos', 'motogp_oro1_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('equipos', 'motogp_oro2_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('equipos', 'motogp_plata1_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('equipos', 'motogp_plata2_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('equipos', 'moto2_oro1_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('equipos', 'moto2_oro2_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('equipos', 'moto2_plata1_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('equipos', 'moto2_plata2_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('equipos', 'moto3_oro1_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('equipos', 'moto3_oro2_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('equipos', 'moto3_plata1_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('equipos', 'moto3_plata2_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_equipos_id'), 'equipos', ['id'], unique=False)
    op.drop_constraint(op.f('equipos_capitan_id_fkey'), 'equipos', type_='foreignkey')
    op.drop_constraint(op.f('equipos_piloto_oro1_id_fkey'), 'equipos', type_='foreignkey')
    op.drop_constraint(op.f('equipos_piloto_bronce_id_fkey'), 'equipos', type_='foreignkey')
    op.drop_constraint(op.f('equipos_piloto_oro2_id_fkey'), 'equipos', type_='foreignkey')
    op.drop_constraint(op.f('equipos_piloto_plata2_id_fkey'), 'equipos', type_='foreignkey')
    op.drop_constraint(op.f('equipos_piloto_plata1_id_fkey'), 'equipos', type_='foreignkey')
    op.drop_column('equipos', 'piloto_plata2_id')
    op.drop_column('equipos', 'piloto_oro2_id')
    op.drop_column('equipos', 'capitan_id')
    op.drop_column('equipos', 'piloto_oro1_id')
    op.drop_column('equipos', 'piloto_plata1_id')
    op.drop_column('equipos', 'piloto_bronce_id')
    op.alter_column('liga_usuarios', 'liga_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('liga_usuarios', 'usuario_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_liga_usuarios_id'), 'liga_usuarios', ['id'], unique=False)
    op.create_index(op.f('ix_ligas_id'), 'ligas', ['id'], unique=False)
    op.create_index(op.f('ix_pilotos_id'), 'pilotos', ['id'], unique=False)
    op.alter_column('resultados', 'carrera_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('resultados', 'piloto_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_resultados_id'), 'resultados', ['id'], unique=False)
    op.drop_column('resultados', 'puntos_fantasy')
    op.create_index(op.f('ix_usuarios_id'), 'usuarios', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usuarios_id'), table_name='usuarios')
    op.add_column('resultados', sa.Column('puntos_fantasy', sa.NUMERIC(precision=6, scale=2), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_resultados_id'), table_name='resultados')
    op.alter_column('resultados', 'piloto_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('resultados', 'carrera_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_pilotos_id'), table_name='pilotos')
    op.drop_index(op.f('ix_ligas_id'), table_name='ligas')
    op.drop_index(op.f('ix_liga_usuarios_id'), table_name='liga_usuarios')
    op.alter_column('liga_usuarios', 'usuario_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('liga_usuarios', 'liga_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('equipos', sa.Column('piloto_bronce_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('equipos', sa.Column('piloto_plata1_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('equipos', sa.Column('piloto_oro1_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('equipos', sa.Column('capitan_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('equipos', sa.Column('piloto_oro2_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('equipos', sa.Column('piloto_plata2_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('equipos_piloto_plata1_id_fkey'), 'equipos', 'pilotos', ['piloto_plata1_id'], ['id'])
    op.create_foreign_key(op.f('equipos_piloto_plata2_id_fkey'), 'equipos', 'pilotos', ['piloto_plata2_id'], ['id'])
    op.create_foreign_key(op.f('equipos_piloto_oro2_id_fkey'), 'equipos', 'pilotos', ['piloto_oro2_id'], ['id'])
    op.create_foreign_key(op.f('equipos_piloto_bronce_id_fkey'), 'equipos', 'pilotos', ['piloto_bronce_id'], ['id'])
    op.create_foreign_key(op.f('equipos_piloto_oro1_id_fkey'), 'equipos', 'pilotos', ['piloto_oro1_id'], ['id'])
    op.create_foreign_key(op.f('equipos_capitan_id_fkey'), 'equipos', 'pilotos', ['capitan_id'], ['id'])
    op.drop_index(op.f('ix_equipos_id'), table_name='equipos')
    op.alter_column('equipos', 'moto3_plata2_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('equipos', 'moto3_plata1_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('equipos', 'moto3_oro2_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('equipos', 'moto3_oro1_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('equipos', 'moto2_plata2_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('equipos', 'moto2_plata1_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('equipos', 'moto2_oro2_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('equipos', 'moto2_oro1_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('equipos', 'motogp_plata2_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('equipos', 'motogp_plata1_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('equipos', 'motogp_oro2_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('equipos', 'motogp_oro1_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('equipos', 'temporada',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('equipos', 'carrera_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('equipos', 'usuario_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_carreras_id'), table_name='carreras')
    op.drop_index(op.f('ix_pronosticos_id'), table_name='pronosticos')
    op.drop_table('pronosticos')
    # ### end Alembic commands ###
