"""añade ubicación y últimos ganadores a circuitos

Revision ID: a260a8958135
Revises: b31f74d12799
Create Date: 2026-08-12 14:14:29.213390

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a260a8958135'
down_revision: Union[str, Sequence[str], None] = 'b31f74d12799'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('circuitos', sa.Column('ubicacion', sa.String(length=150), nullable=True))
    op.add_column('circuitos', sa.Column('ultimo_ganador_motogp', sa.String(length=100), nullable=True))
    op.add_column('circuitos', sa.Column('ultimo_ganador_moto2', sa.String(length=100), nullable=True))
    op.add_column('circuitos', sa.Column('ultimo_ganador_moto3', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('circuitos', 'ultimo_ganador_moto3')
    op.drop_column('circuitos', 'ultimo_ganador_moto2')
    op.drop_column('circuitos', 'ultimo_ganador_motogp')
    op.drop_column('circuitos', 'ubicacion')
    # ### end Alembic commands ###
