"""añade reset de contraseña y bloqueo por intentos

Revision ID: b31f74d12799
Revises: fc277f5794f4
Create Date: 2026-08-12 08:18:50.032801

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b31f74d12799'
down_revision: Union[str, Sequence[str], None] = 'fc277f5794f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('token_reset_password', sa.String(length=64), nullable=True))
    op.add_column('usuarios', sa.Column('token_reset_expira', sa.DateTime(), nullable=True))
    op.add_column('usuarios', sa.Column('intentos_login_fallidos', sa.Integer(), nullable=False, server_default=sa.text('0')))
    op.add_column('usuarios', sa.Column('bloqueado_hasta', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'bloqueado_hasta')
    op.drop_column('usuarios', 'intentos_login_fallidos')
    op.drop_column('usuarios', 'token_reset_expira')
    op.drop_column('usuarios', 'token_reset_password')
    # ### end Alembic commands ###
