"""añade tabla circuitos y circuito_id en carreras

Revision ID: d80403fadf2a
Revises: 8f38f93de710
Create Date: 2026-07-28 14:08:42.809278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd80403fadf2a'
down_revision: Union[str, Sequence[str], None] = '8f38f93de710'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('circuitos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('pais', sa.String(length=50), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('curvas_izquierda', sa.Integer(), nullable=True),
    sa.Column('curvas_derecha', sa.Integer(), nullable=True),
    sa.Column('velocidad_max_kmh', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index(op.f('ix_circuitos_id'), 'circuitos', ['id'], unique=False)
    op.add_column('carreras', sa.Column('circuito_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'carreras', 'circuitos', ['circuito_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'carreras', type_='foreignkey')
    op.drop_column('carreras', 'circuito_id')
    op.drop_index(op.f('ix_circuitos_id'), table_name='circuitos')
    op.drop_table('circuitos')
    # ### end Alembic commands ###
