"""añade imagen_url a circuitos

Revision ID: e17799bb6ec4
Revises: 427606013f48
Create Date: 2026-08-13 14:10:17.441388

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e17799bb6ec4'
down_revision: Union[str, Sequence[str], None] = '427606013f48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('circuitos', sa.Column('imagen_url', sa.String(length=300), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('circuitos', 'imagen_url')
    # ### end Alembic commands ###
