"""añade es_global a ligas

Revision ID: ee94486fb303
Revises: 6f577bd94a18
Create Date: 2026-08-07 11:00:04.035889

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee94486fb303'
down_revision: Union[str, Sequence[str], None] = '6f577bd94a18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ligas', sa.Column('es_global', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ligas', 'es_global')
    # ### end Alembic commands ###
