"""añade verificación de email a usuarios

Revision ID: fc277f5794f4
Revises: ee94486fb303
Create Date: 2026-08-11 13:14:19.052612

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc277f5794f4'
down_revision: Union[str, Sequence[str], None] = 'ee94486fb303'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('email_verificado', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('usuarios', sa.Column('token_verificacion', sa.String(length=64), nullable=True))
    op.add_column('usuarios', sa.Column('intentos_login_sin_verificar', sa.Integer(), nullable=False, server_default=sa.text('0')))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'intentos_login_sin_verificar')
    op.drop_column('usuarios', 'token_verificacion')
    op.drop_column('usuarios', 'email_verificado')
    # ### end Alembic commands ###
