-- Borrar piloto de prueba ya insertado
DELETE FROM pilotos;

-- MotoGP 2026 (22 pilotos)
INSERT INTO pilotos (nombre, numero, categoria, equipo, nacionalidad, precio, activo) VALUES
('Marc Márquez',          93, 'MotoGP', 'Ducati Lenovo Team',              'España',      30.00, true),
('Francesco Bagnaia',      1, 'MotoGP', 'Ducati Lenovo Team',              'Italia',      28.00, true),
('Jorge Martín',          89, 'MotoGP', 'Aprilia Racing',                  'España',      27.00, true),
('Marco Bezzecchi',       72, 'MotoGP', 'Aprilia Racing',                  'Italia',      24.00, true),
('Fermín Aldeguer',       54, 'MotoGP', 'BK8 Gresini Racing',              'España',      23.00, true),
('Álex Márquez',          73, 'MotoGP', 'BK8 Gresini Racing',              'España',      22.00, true),
('Fabio Di Giannantonio', 49, 'MotoGP', 'VR46 Racing Team',                'Italia',      21.00, true),
('Franco Morbidelli',     21, 'MotoGP', 'VR46 Racing Team',                'Italia',      18.00, true),
('Toprak Razgatlioglu',   54, 'MotoGP', 'Prima Pramac Yamaha',             'Turquía',     22.00, true),
('Jack Miller',           43, 'MotoGP', 'Prima Pramac Yamaha',             'Australia',   18.00, true),
('Fabio Quartararo',      20, 'MotoGP', 'Monster Yamaha',                  'Francia',     20.00, true),
('Álex Rins',             42, 'MotoGP', 'Monster Yamaha',                  'España',      17.00, true),
('Pedro Acosta',          31, 'MotoGP', 'Red Bull KTM',                    'España',      25.00, true),
('Brad Binder',           33, 'MotoGP', 'Red Bull KTM',                    'Sudáfrica',   20.00, true),
('Enea Bastianini',       23, 'MotoGP', 'KTM Tech3',                       'Italia',      19.00, true),
('Maverick Viñales',      12, 'MotoGP', 'KTM Tech3',                       'España',      19.00, true),
('Ai Ogura',              79, 'MotoGP', 'Trackhouse Racing Aprilia',       'Japón',       21.00, true),
('Johann Zarco',           5, 'MotoGP', 'LCR Honda',                       'Francia',     17.00, true),
('Diogo Moreira',         89, 'MotoGP', 'LCR Honda',                       'Brasil',      16.00, true),
('Luca Marini',           10, 'MotoGP', 'Repsol Honda',                    'Italia',      18.00, true),
('Joan Mir',              36, 'MotoGP', 'Repsol Honda',                    'España',      17.00, true),
('Somkiat Chantra',       35, 'MotoGP', 'Idemitsu Honda LCR',              'Tailandia',   15.00, true),

-- Moto2 2026 (28 pilotos)
('Áaron Canet',           44, 'Moto2', 'Marc VDS Team',                    'España',      18.00, true),
('Deniz Öncü',            53, 'Moto2', 'Marc VDS Team',                    'Turquía',     16.00, true),
('Manuel González',       23, 'Moto2', 'Dynavolt Intact GP',               'España',      17.00, true),
('Celestino Vietti',      13, 'Moto2', 'Red Bull KTM Ajo',                 'Italia',      17.00, true),
('José Antonio Rueda',    99, 'Moto2', 'Red Bull KTM Ajo',                 'España',      15.00, true),
('Daniel Holgado',         6, 'Moto2', 'CFMoto Aspar Team',                'España',      16.00, true),
('David Alonso',          80, 'Moto2', 'CFMoto Aspar Team',                'Colombia',    17.00, true),
('Alonso López',          21, 'Moto2', 'Gresini Racing Moto2',             'España',      15.00, true),
('Sergio García',         11, 'Moto2', 'Gresini Racing Moto2',             'España',      14.00, true),
('Jake Dixon',            96, 'Moto2', 'CFMOTO Inde Aspar',                'Reino Unido', 14.00, true),
('Ángel Piqueras',        52, 'Moto2', 'Leopard Racing',                   'España',      13.00, true),
('Luca Lunetta',          58, 'Moto2', 'SIC58 Squadra Corse',              'Italia',      12.00, true),
('Taiyo Furusato',        11, 'Moto2', 'Honda Team Asia',                  'Japón',       12.00, true),
('Alberto Ferrández',      7, 'Moto2', 'Fantic Racing',                    'España',      11.00, true),

-- Moto3 2026 (26 pilotos)
('Ryusei Yamanaka',        6, 'Moto3', 'MT Helmets MSI',                   'Japón',       13.00, true),
('Iván Ortolá',           48, 'Moto3', 'MT Helmets MSI',                   'España',      14.00, true),
('Álvaro Carpe',          77, 'Moto3', 'Red Bull KTM Ajo',                 'España',      13.00, true),
('Brian Uriarte',         27, 'Moto3', 'Red Bull KTM Ajo',                 'España',      11.00, true),
('Máximo Quiles',         82, 'Moto3', 'CFMoto Aspar Team',                'España',      12.00, true),
('Marco Morelli',         74, 'Moto3', 'CFMoto Aspar Team',                'Italia',      10.00, true),
('David Muñoz',           64, 'Moto3', 'Dynavolt Intact GP',               'España',      12.00, true),
('David Almansa',         22, 'Moto3', 'Dynavolt Intact GP',               'España',      11.00, true),
('Nicola Carraro',        10, 'Moto3', 'Snipers Team',                     'Italia',      10.00, true),
('Jesús Ríos',            55, 'Moto3', 'Snipers Team',                     'España',      10.00, true),
('Guido Pini',            16, 'Moto3', 'Leopard Racing',                   'Italia',      11.00, true),
('Matteo Bertelle',       18, 'Moto3', 'Angeluss MTA Team',                'Italia',      10.00, true),
('Joel Kelso',            88, 'Moto3', 'GRYD MLav Racing',                 'Australia',   10.00, true),
('Eddie O''Shea',          8, 'Moto3', 'GRYD MLav Racing',                 'Reino Unido', 10.00, true),
('Cormac Buchanan',       14, 'Moto3', 'Boe Motorsports',                  'Nueva Zelanda',10.00, true),
('Ruché Moodley',         21, 'Moto3', 'Boe Motorsports',                  'Sudáfrica',   10.00, true),
('Scott Ogden',           19, 'Moto3', 'CIP',                              'Reino Unido', 10.00, true),
('Adrián Cruces',         45, 'Moto3', 'CIP',                              'España',      10.00, true),
('Hakim Danish',          77, 'Moto3', 'Frinsa MT Helmets MSI',            'Malasia',     10.00, true),
('Rico Salmela',          33, 'Moto3', 'Red Bull KTM Tech3',               'Finlandia',   10.00, true),
('Zen Mitani',            63, 'Moto3', 'Honda Team Asia',                  'Japón',       10.00, true),
('Veda Pratama',          42, 'Moto3', 'Honda Team Asia',                  'Indonesia',   10.00, true),
('Casey O''Gorman',       25, 'Moto3', 'SIC58 Squadra Corse',              'Irlanda',     10.00, true);