apiVersion: apps/v1
kind: Deployment
metadata:
  name: pitlane-api
  labels:
    app: pitlane-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pitlane-api
  template:
    metadata:
      labels:
        app: pitlane-api
    spec:
      containers:
      - name: pitlane-api
        image: europe-west1-docker.pkg.dev/pitlane-fantasy/pitlane-repo/pitlane-fantasy-api:v17
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: pitlane-secrets
              key: DATABASE_URL
        - name: APP_NAME
          valueFrom:
            secretKeyRef:
              name: pitlane-secrets
              key: APP_NAME
        - name: VERSION
          valueFrom:
            secretKeyRef:
              name: pitlane-secrets
              key: VERSION
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: pitlane-secrets
              key: SECRET_KEY
        - name: SENDGRID_API_KEY
          valueFrom:
            secretKeyRef:
              name: pitlane-secrets
              key: SENDGRID_API_KEY
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 15
          periodSeconds: 10
      - name: pitlane-api-nginx
        image: europe-west1-docker.pkg.dev/pitlane-fantasy/pitlane-repo/pitlane-api-nginx:v1
        ports:
        - containerPort: 443
        - containerPort: 80
        volumeMounts:
        - name: tls-certs
          mountPath: /etc/nginx/certs
          readOnly: true
      volumes:
      - name: tls-certs
        secret:
          secretName: pitlane-tls-origin
          items:
          - key: tls.crt
            path: tls.crt
          - key: tls.key
            path: tls.key
