apiVersion: apps/v1
kind: Deployment
metadata:
  name: pitlane-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pitlane-frontend
  template:
    metadata:
      labels:
        app: pitlane-frontend
    spec:
      containers:
      - name: pitlane-frontend
        image: europe-west1-docker.pkg.dev/pitlane-fantasy/pitlane-repo/pitlane-frontend:v12
        ports:
        - containerPort: 80
        - containerPort: 443
        volumeMounts:
        - name: tls-certs
          mountPath: /etc/nginx/certs
          readOnly: true
      volumes:
      - name: tls-certs
        secret:
          secretName: pitlane-tls-origin
          items:
          - key: tls.crt
            path: tls.crt
          - key: tls.key
            path: tls.key
---
apiVersion: v1
kind: Service
metadata:
  name: pitlane-frontend-service
spec:
  type: LoadBalancer
  selector:
    app: pitlane-frontend
  ports:
  - name: http
    port: 80
    targetPort: 80
  - name: https
    port: 443
    targetPort: 443
